In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [3]:
car_data = pd.read_csv("car_fuel_efficiency_2026.csv")

In [4]:
car_data.tail()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
9995,2005,USA,Gasoline,All-wheel drive,4,2470,6,271.0,4690,18.9,27.4
9996,1993,Asia,Gasoline,All-wheel drive,2,2300,6,244.0,4370,19.0,30.0
9997,2014,USA,Gasoline,All-wheel drive,3,2480,6,267.0,4590,18.4,28.1
9998,2004,USA,Hybrid,Rear-wheel drive,5,2180,6,270.0,4450,20.9,32.2
9999,2011,USA,Diesel,Front-wheel drive,4,2380,6,295.0,4370,17.6,30.2

In [5]:
car_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   model_year           10000 non-null  int64
 1   origin               10000 non-null  object
 2   fuel_type            10000 non-null  object
 3   drivetrain           10000 non-null  object
 4   num_doors            10000 non-null  int64
 5   engine_displacement  10000 non-null  int64
 6   num_cylinders        10000 non-null  int64
 7   horsepower           9123 non-null   float64
 8   vehicle_weight       10000 non-null  int64
 9   acceleration         9736 non-null   float64
 10  fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(3), int64(5), object(3)
memory usage: 859.5+ KB

In [6]:
car_data.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [7]:
car_data.index

RangeIndex(start=0, stop=10000, step=1)

In [8]:
car_data.columns

Index(['model_year', 'origin', 'fuel_type', 'drivetrain', 'num_doors',
       'engine_displacement', 'num_cylinders', 'horsepower', 'vehicle_weight',
       'acceleration', 'fuel_efficiency_mpg'],
      dtype='object')

In [9]:
car_data["fuel_type"]

0       Gasoline
1         Diesel
2       Gasoline
3       Gasoline
4         Diesel
          ...
9995    Gasoline
9996    Gasoline
9997    Gasoline
9998      Hybrid
9999      Diesel
Name: fuel_type, Length: 10000, dtype: object

In [10]:
car_data[
    (car_data["origin"] == "Asia") &
    (car_data["fuel_efficiency_mpg"] == car_data["fuel_efficiency_mpg"].max())
]

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
6354,2022,Asia,Diesel,Front-wheel drive,4,1990,6,225.0,3870,17.2,41.2

In [11]:
car_data["horsepower"]

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [12]:
horsepower_median = car_data["horsepower"].median()
horsepower_median

np.float64(254.0)

In [13]:
horsepower_mode = car_data["horsepower"].mode()[0]
horsepower_mode

np.float64(252.0)

In [14]:
car_data["horsepower"] = car_data["horsepower"].fillna(horsepower_mode)

In [15]:
horsepower_median_filled = car_data["horsepower"].median()
horsepower_median_filled

np.float64(252.0)

In [16]:
import numpy as np

asia_cars = car_data[car_data["origin"] == "Asia"]
subset = asia_cars[["vehicle_weight", "model_year"]]
first_7 = subset.head(7)
X = first_7.values
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [17]:
XTX = X.T @ X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [18]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [19]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [20]:
w = XTX_inv @ X.T @ y
w

array([0.13644777, 0.2327492 ])

In [21]:
w_sum = w.sum()
w_sum

np.float64(0.36919696904925486)